### ISSUE TITLE
[1.19.2] Crash out of no where while exploring world

### ISSUE THREAD

**Issue by BugmanBugman** [DragonsPlusMinecraft/VisualityReforged#1]
https://bytebin.lucko.me/hveH3oGJp2

**Comment by RaymondBlaze** [comment]
I can't reproduce the crash with Forge 43.1.52 and Visuality-0.6-mc1.19 only, both in develop and production environment.

The best strategy to test what exactly is going wrong, is to split your mods into 2 parts, test with each part and repeat this process, until we are able to locate a fairly small range of mods.

**Comment by RaymondBlaze** [comment]
Visuality: Reforge-1.0-mc1.19+ has released, there're major changes in this update.
Though I still can't reproduce the crash, but maybe you'll want to try with the new version just in case it's fixed accidentally.

**Comment by RaymondBlaze** [comment]
See #2
