### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by CheezBallzFTW** [DragonsPlusMinecraft/VisualityReforged#10]
https://gist.github.com/CheezBallzFTW/c9f63f65219f030e66c374f803682dc7

**Comment by 0BLIQU3** [comment]
I'm currently having the same issue.

**Comment by MrBOOMberMAN** [comment]
Same Here

**Comment by HanatakeYurii** [comment]
I'm joining the club, same error here

**Comment by R3ner** [comment]
seems like no one is trying to fix this...

**Comment by MarbleGateKeeper** [comment]
Dupelicate of #7
