### ISSUE TITLE
1.18.2 crashed

### ISSUE THREAD

**Issue by Ryuushen** [DragonsPlusMinecraft/VisualityReforged#14]
Minecraft version: 1.18.2
Forge version: 40.2.14 
Mod version: 1.0

Embedium, Modernfix, Visuality Reforged, Blueprint installed and crashed when it's raining near the lake

[crash-2023-12-26_23.26.00-client.txt](https://github.com/DragonsPlusMinecraft/VisualityReforged/files/13781493/crash-2023-12-26_23.26.00-client.txt)

**Comment by OcrSu** [comment]
> Minecraft version: 1.18.2 Forge version: 40.2.14 Mod version: 1.0
> 
> Embedium, Modernfix, Visuality Reforged, Blueprint installed and crashed when it's raining near the lake
> 
> [crash-2023-12-26_23.26.00-client.txt](https://github.com/DragonsPlusMinecraft/VisualityReforged/files/13781493/crash-2023-12-26_23.26.00-client.txt)

![image](https://github.com/DragonsPlusMinecraft/VisualityReforged/assets/75876201/328769d0-5d01-495f-a1f2-2fd7ed536078)

1.18.2 only have 1.0Version......

**Comment by MarbleGateKeeper** [comment]
Please install this mod on server side.
