### ISSUE TITLE
Heavily impact loading time of chunk (huge modpack killer)

### ISSUE THREAD

**Issue by zoqin** [DragonsPlusMinecraft/VisualityReforged#16]
Heavily impact loading time of chunk as such down the line it could be realy messing up with world generation mod 

I had issue with a heavy modpack getting ticking issue realy often when exploring involving waiting several minute at world border to see chunk load with a fifth generation ryzen 9 CPU

I have tested undreads of mods and Visuality Reforged stand out at one of the triggerng actor of this issue

You can test this easily by flying at 8x speed high in the air through the world without visuality reforged my character flicker sometime shorlty disapered but at a point the chunk loading just come back
with visualityReforged you will disapered then if you fly long enough the world will brick then if you have Neruina it will load back down the line else, you need to stop the game with task manager, in both case you are good to delet your word as it is corrupt and structure will spawn at wrong place and world gen too leading to cliff being cute clean by flat plato then floating block and sometime multiple structure at the same place fighting for the position

It would be kinda funny if it was deliberated and didnt impact loading time

**Comment by MarbleGateKeeper** [comment]
Please provide debug.log so I can check what happened. And a Spark profiling log is suggested.
Visuality has nothing to do with world generation. It's strange.

**Comment by zoqin** [comment]
**You where right,** after a lot of tinkering I found today that my issue was garbage collection, **allocating to much ram didn't triggered GC enough** and when it did he would instantly froze. While Visuality Reforge have nothing to do with world generation, **having it enable just use enough ram to trigger GC quickly on my benchmark briking the world generation**
 
Exploring long enough with other mod triggered the same issue once the GC finally triggered

**The solution is to lower RAM allocation to trigger GC more often so Java don't froze** while processing the high amount of data, I was allocating 20go and I crank it back down to 12go, making other garbage collection optimization would probably help, as long as Java doesn't need to handle 20Go at once

**Comment by zoqin** [comment]
Thanks for reading my issue and being open to help me, it was very kind of you, im excited to experience your mod in a stable scenario 

I wish you a really good day

**Comment by MarbleGateKeeper** [comment]
Thanks for your detailed reply!
