### ISSUE TITLE
CRASH 1.19.3: Reforged (visuality) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Ariostraza** [DragonsPlusMinecraft/VisualityReforged#3]
Minecraft 1.19.3 (Forge 44.1.2)
Caused by: java.lang.NoClassDefFoundError: com/mojang/math/Vector3f

Crash report: [[Link]](https://justpaste.it/6fegu)

**Comment by ghost** [comment]
Same here

**Comment by RaymondBlaze** [comment]
Fixed as of version 2.0 now supporting 1.19.3 and 1.19.4
