### ISSUE TITLE
[Crash-report] Window crashed when player respawned during rainstorm.

### ISSUE THREAD

**Issue by Cixon** [DragonsPlusMinecraft/VisualityReforged#4]
Hey! I really love this mod, I find it a better alternative to the other visual mods out there.
Anyway, I'm using a mod called [Weather, Storms & Tornadoes](https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes) which changes the way weather works.
I was wondering if you could investigate this crash-report please? Thank you!

Crash-report:
[crash-2023-02-19_23.48.16-client.txt](https://github.com/ChannelingMC/visuality-forge/files/10780032/crash-2023-02-19_23.48.16-client.txt)

Log (line 3,580)
[latest.log](https://github.com/ChannelingMC/visuality-forge/files/10780038/latest.log)

**Comment by Cixon** [comment]
**Environments:**

I'm using the latest 1.18.2 version.
This crash occurred on the server and no, the server does not have the mod installed.

**Comment by Cixon** [comment]
Yeah so it appears the visuality water dripping effect that occurs on bodies of water crashes because it cannot calculate the rain with the Weather & Tornado mod. I think there just needs to be a compatibility patch and it will be okay.

**Comment by RaymondBlaze** [comment]
> This crash occurred on the server and no, the server does not have the mod installed.

Duplicate with #2.
Due to Forge's registry sync mechanics, it's impossible to add new particle types on client only.
I am planning an overhaul for the mod to make it completely client side only, but currently I haven't started the work yet.
For now, just install it on both sides.
