### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by MrBOOMberMAN** [DragonsPlusMinecraft/VisualityReforged#8]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "plus.dragons.visuality.registry.VisualityRegistries.PARTICLE_TYPES" is null

[crash-2023-05-17_11.27.59-client.txt](https://github.com/DragonsPlusMinecraft/visuality-forge/files/11496968/crash-2023-05-17_11.27.59-client.txt)

**Comment by m0thknight** [comment]
Had this same issue.
[crash-2023-05-31_21.20.13-client.txt](https://github.com/DragonsPlusMinecraft/visuality-forge/files/11620914/crash-2023-05-31_21.20.13-client.txt)

**Comment by PvtFudgepants** [comment]
I have this happen too, and weirdly enough it seems to only happen sometimes? If it starts happening I disable the mod, and then later on I can reenable it and it works again.

**Comment by MarbleGateKeeper** [comment]
Dupelicate of #7
